/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WissenRouteImport } from './routes/wissen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatAgentIdRouteImport } from './routes/chat.$agentId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WissenRoute = WissenRouteImport.update({
  id: '/wissen',
  path: '/wissen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAgentIdRoute = ChatAgentIdRouteImport.update({
  id: '/chat/$agentId',
  path: '/chat/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wissen': typeof WissenRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wissen': typeof WissenRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wissen': typeof WissenRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$agentId': typeof ChatAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wissen' | '/api/chat' | '/chat/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wissen' | '/api/chat' | '/chat/$agentId'
  id: '__root__' | '/' | '/wissen' | '/api/chat' | '/chat/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WissenRoute: typeof WissenRoute
  ApiChatRoute: typeof ApiChatRoute
  ChatAgentIdRoute: typeof ChatAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wissen': {
      id: '/wissen'
      path: '/wissen'
      fullPath: '/wissen'
      preLoaderRoute: typeof WissenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$agentId': {
      id: '/chat/$agentId'
      path: '/chat/$agentId'
      fullPath: '/chat/$agentId'
      preLoaderRoute: typeof ChatAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WissenRoute: WissenRoute,
  ApiChatRoute: ApiChatRoute,
  ChatAgentIdRoute: ChatAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
